name: flutter_annotations
description: Sketchers, annotate ideas, and save information to reuse later is now easier with Flutter Annotations..
version: 1.0.0
author: Edvaldo Martins <edvaldomartins.developer@gmail.com>
homepage: https://github.com/EdvaldoMartins/flutter_annotations

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.6
#  get_it: ^1.0.3
#  provider: ^2.0.1
  fluttertoast: ^3.1.0
  intl: ^0.15.8
  backdrop: ^0.1.8
  flutter_lifecycle_state: ^1.0.0
  expandable: ^3.0.0+1
  random_color: ^1.0.3
  flutter_svg: ^0.14.1
  shared_preferences: ^0.4.2
  avatar_letter: ^1.0.0
  share: ^0.6.2+1
  flutter_bloc: ^0.21.0
  equatable: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Font
      fonts:
        - asset: assets/fonts/font2.ttf

    - family: FontLetra
      fonts:
        - asset: assets/fonts/icomoon.ttf
#        - asset: assets/fonts/font_letra.ttf
  assets:
    - assets/locale/i18n_en.json
    - assets/locale/i18n_pt.json
    - assets/locale/i18n_es.json
    - assets/icons/delete.svg
    - assets/icons/detail.svg
    - assets/icons/more.svg
    - assets/icons/cancel.svg
    - assets/icons/save.svg
    - assets/icons/add.svg
    - assets/icons/arrow-left.svg
    - assets/icons/check.svg
    - assets/icons/edit.svg
    - assets/icons/eye.svg
    - assets/icons/save.svg
    - assets/icons/search.svg
    - assets/icons/send.svg
    - assets/icons/sliders.svg
    - assets/icons/delete.svg
    - assets/icons/sort.svg
    - assets/icons/lock.svg
    - assets/icons/unlock.svg
    - assets/icons/color.svg
    - assets/icons/info.svg
    - assets/icons/editor.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
